
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../types_db'; // This will be generated by Supabase CLI

// IMPORTANT: As per your request, these are hardcoded. This is not a recommended practice for production applications.
const supabaseUrl = 'https://dilxuwnviffjwgktxgaw.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbHh1d252aWZmandna3R4Z2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MTY3MjYsImV4cCI6MjA3NzE5MjcyNn0.ZDUKUks_bGWMUrb-E2DEe7msAQVhlEVE8LAf4jyUakU';

if (!supabaseUrl || !supabaseAnonKey) {
  // This check is kept just in case the hardcoded values are accidentally removed.
  throw new Error('Supabase URL and Anon Key must be provided.');
}

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);